SET(PROTONC_FOUND "NO")

SET(PROTONC_SEARCH_PATHS
	/usr/local/
    /sw/
	/usr/
)

FIND_PATH(PROTONC_INCLUDE_DIR
	NAMES messenger.h
	PATH_SUFFIXES /include/proton/
	PATHS ${PROTONC_SEARCH_PATHS}
)

FIND_LIBRARY(PROTONC_LIBRARY
	NAMES qpid-proton
	PATH_SUFFIXES /lib/
	PATHS ${PROTONC_SEARCH_PATHS}
)

IF(PROTONC_LIBRARY AND PROTONC_INCLUDE_DIR)
  SET(PROTONC_FOUND "YES")
ENDIF(PROTONC_LIBRARY AND PROTONC_INCLUDE_DIR)

IF(PROTONC_LIBRARY)
	SET(CMAKE_REQUIRED_LIBRARIES ${PROTONC_LIBRARY})
ENDIF(PROTONC_LIBRARY)

IF(PROTONC_FOUND)
  IF(NOT PROTONC_FIND_QUIETLY)
    MESSAGE(STATUS "Found PROTONC: ${PROTONC_LIBRARY},${PROTONC_LIBRARY}")
  ENDIF(NOT PROTONC_FIND_QUIETLY)
ELSE(PROTONC_FOUND)
  IF(PROTONC_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find PROTONC Library")
  ENDIF(PROTONC_FIND_REQUIRED)
ENDIF(PROTONC_FOUND)

